// program number: 30
// Student Name: Keshav Singhal; Register Number: IMT2018511
// Date: 25/02/2021
// Description : a program to run a script at a specific time using a Daemon process.
#include<stdio.h>
#include<unistd.h>
#include<stdlib.h>
#include<sys/time.h>
#include<sys/stat.h>

int main(){
	int pid = fork();

	if(pid == 0)
	{
		int sid = setsid(); //Creating a Unique Session ID (SID).
	
		chdir("/"); // Changing The Working Directory
				//The current working directory should be changed to some place 
				//that is guaranteed to always be there.

		umask(0); // changing the file mode mask. By setting the umask to 0, 
			  //we will have full access to the files generated by the daemon.
		printf("child pid : %d\n",getpid());
		while(1){
			sleep(5);
			printf("this is Daemon Process \n");
			printf("ppid : %d\n", getppid());
		}
	}
	else{
		exit(0);
	}

}